// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutHo_yapdBu2IglYBRCEfHvPem2Ng_Rk',
    appId: '1:293046752665:web:d7e30703ef9c4f924bef08',
    messagingSenderId: '293046752665',
    projectId: 'ln5525',
    authDomain: 'ln5525.firebaseapp.com',
    storageBucket: 'ln5525.appspot.com',
    measurementId: 'G-R6D2JJD6DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6TqGvU3_3rhEwZEOdybYEbjq-a02g8b8',
    appId: '1:293046752665:android:d53afcf74580e2bb4bef08',
    messagingSenderId: '293046752665',
    projectId: 'ln5525',
    storageBucket: 'ln5525.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhuNi9mR-0uyKYsQ2d7_MtQm9NdnTON9g',
    appId: '1:293046752665:ios:f9211b2ea655f66c4bef08',
    messagingSenderId: '293046752665',
    projectId: 'ln5525',
    storageBucket: 'ln5525.appspot.com',
    iosBundleId: 'com.example.lnbac5525',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhuNi9mR-0uyKYsQ2d7_MtQm9NdnTON9g',
    appId: '1:293046752665:ios:f9211b2ea655f66c4bef08',
    messagingSenderId: '293046752665',
    projectId: 'ln5525',
    storageBucket: 'ln5525.appspot.com',
    iosBundleId: 'com.example.lnbac5525',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCutHo_yapdBu2IglYBRCEfHvPem2Ng_Rk',
    appId: '1:293046752665:web:b295fb9ee3088b644bef08',
    messagingSenderId: '293046752665',
    projectId: 'ln5525',
    authDomain: 'ln5525.firebaseapp.com',
    storageBucket: 'ln5525.appspot.com',
    measurementId: 'G-ZHFK7TP4H3',
  );
}
